variables:
  # Product
  PRODUCT: pip-apply
  # Config
  BUILD_TYPE: MAVEN
  MAVEN_IMAGE: "maven:3-openjdk-17"
  MVN_OPTS: "-DLOG_LEVEL=INFO -DtargetClasses=${PITEST_TARGET_CLASSES} -DtargetTests=${PITEST_TARGET_TEST_CLASSES} -DexcludedTestClasses=${PITEST_EXCLUDED_TEST_CLASSES}"
  MVN_CLI_OPTS: "--batch-mode"
  REPO_OWNER: "Team Goldcrest"
  REPO_PATTERN: "V3 CI"
  GITHUB_REPO_NAME: ms-pip-pdf-generator
  PIP_APPLY_MOCKS_NAME: pip-apply-mocks
  PIP_APPLY_MOCKS_VERSION: "develop"
  MS_HTML_TO_PDFA_NAME: ms-html-to-pdfa
  MS_HTML_TO_PDFA_VERSION: "develop"
  # Duplicated config from pom to run in pipeline
  PITEST_TARGET_CLASSES: "uk.gov.dwp.health.pip.pdf.generator.*"
  PITEST_TARGET_TEST_CLASSES: "uk.gov.dwp.health.pip.pdf.generator.*"
  PITEST_EXCLUDED_TEST_CLASSES: "**.*IT"

stages:
  - update-version
  - code-quality
  - code-test
  - application-build
  - code-analysis
  - image-build
  - container-image-test
  - component-test
  - image-push
  - update-project-metadata
  - create-schedules
  - update-changelog
  - release-mr-main
  - release-tag
  - release-update-version
  - release-mr-develop
  - open-source

include:
  - local: "/gitlab-ci/includes.yml"

required-fragment-check:
  variables:
    RULESET: MAVEN_CI

.prepare-test: &prepare-test
  before_script:
    - apk add --no-cache py-pip jq
    - pip install awscli
    - eval $(aws ecr get-login --no-include-email --region eu-west-2 | sed 's|https://||')
    - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
    - export GITLAB_IMAGE="$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:${CI_COMMIT_SHA:0:8}"
    - export PIP_APPLY_MOCKS_IMAGE=$(aws ssm get-parameter --name "/artifact/$PRODUCT/$PIP_APPLY_MOCKS_NAME/$PIP_APPLY_MOCKS_VERSION" --with-decryption --output json | jq --raw-output '.Parameter.Value')
    - export MS_HTML_TO_PDFA_IMAGE=$(aws ssm get-parameter --name "/artifact/shared/$MS_HTML_TO_PDFA_NAME/$MS_HTML_TO_PDFA_VERSION" --with-decryption --output json | jq --raw-output '.Parameter.Value')

api-test:
  extends: .docker-compose-run
  stage: component-test
  variables:
    DOCKER_COMPOSE_FILE: "docker-compose.yml"
    DOCKER_COMPOSE_COMMAND: "--exit-code-from api-test"
    MVN_OPTS: '-Dmaven.repo.local=~/.m2/repository'
    MVN_M2: "~/.m2"
  <<: *prepare-test
  after_script:
    - docker logout
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./.m2/repository/
  artifacts:
    expire_in: 1 day
    paths:
      - test/reports/
    when: always
    expose_as: 'ms-pip-pdf-generator API Component Test Report'

create-develop-nightly-schedule:
  extends: .add-schedule
  variables:
    SCHEDULE_NAME: Nightly-Develop-CI-Build
    SCHEDULE_BRANCH: develop
    SCHEDULE_CRON: "0 04 * * *"
    RANDOMIZE_MINS: "true"

trivy-container:
  extends: .trivy-container-base

### DEFAULT RUNNER ###
default:
  tags:
    - docker
  image: alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11
