app_name: @project.artifactId@
app_version: @project.version@

spring:
  main:
    banner-mode: 'off'
  jmx:
    enabled: false
  profiles:
    active: local
html:
  pdf:
    generator:
      baseUrl: https://htmltopdf.fha-pip.dev.health-dev.dwpcloud.uk
      endpointPath: generatePdf
      htmlToPdfConformanceLevel: PDFA_1_A

aws:
  s3:
    awsRegion: eu-west-2
    endpointOverride: http://localstack:4566
  encryption:
    kmsOverride: http://ms-mock-kms-service:5678
    dataKey: awssecretkey
  secret:
    accessKey: its-a-secret

s3:
  bucket: pip-bucket
  accessKeyId: awsaccesskey
