########################################################################################
###    Jobs to add project documentation                                             ###
########################################################################################

### ENVIRONMENT
.environment: &environment
  environment:
    name: "$ENVIRONMENT"
    action: prepare

### TRIGGERS
.documentation: &documentation
  rules:
    - if: $DOCUMENTATION == "true"

### METADATA
create-project-badges:
  extends: .create-project-badges-template
  dependencies:
    - todo-check
  <<: *environment
  <<: *documentation
